name: kube-test

on:
  pull_request:
    branches: ['*']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Runs all the presubmission verifications.
      run: make verify
    - name: Build and run tests.
      run: make test
    - name: Build and run integration tests.
      run: make test-integration
