name: kube-test

on:
  pull_request:
    branches: ['*']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Runs all the presubmission verifications.
      run: make verify WHAT=.plugin/pkg/auth/authorizer/rbac/bootstrappolicy
    - name: Build and run tests.
      run: make test WHAT=.plugin/pkg/auth/authorizer/rbac/bootstrappolicy
    - name: Build and run integration tests.
      run: make test-integration WHAT=.plugin/pkg/auth/authorizer/rbac/bootstrappolicy
